name: nbaquiz
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
cached_network_image: ^4.2.0
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0


flutter:


  uses-material-design: true


  assets:
    - assets\pngegg.png
    - assets\NBA-3-Point-Shooting.png
    - assets\michael-jordan.png
    - assets\Screenshot_2.png
    - assets\Reaper.jpg
    - assets\Taça.jpg
    - assets\giphy.gif

